# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

users = User.create!([
  { username: 'Tommy', email: 'tommy@test.com', password: 'password' },
  { username: 'Bobby', email: 'bobby@test.com', password: 'password' },
  { username: 'Sarah', email: 'sarah@test.com', password: 'password' },
  { username: 'Lilly', email: 'lilly@test.com', password: 'password' },
  { username: 'Jimmy', email: 'jimmy@test.com', password: 'password' },
  { username: 'Cammy', email: 'cammy@test.com', password: 'password' },
])

products = Product.create!([
  {
    title: 'Photo 1',
    description: 'Beautiful photo of apartment 1',
    city: 'Paris',
    country: 'France',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 50,
    profit_sharing: 70,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/1.jpg',
    user: users.first
  }, {
    title: 'Photo 2',
    description: 'Large photo of apartment 2',
    city: 'New York',
    country: 'US',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 60,
    profit_sharing: 60,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/2.jpg',
    user: users.first
  }, {
    title: 'Photo 3',
    description: 'Small photo of apartment 3',
    city: 'Abu Dhabi',
    country: 'UAE',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 40,
    profit_sharing: 80,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/3.jpg',
    user: users.first
  }, {
    title: 'Photo 4',
    description: 'Amazing photo of apartment 4',
    city: 'Dubai',
    country: 'UAE',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 100,
    profit_sharing: 20,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/4.jpg',
    user: users.second
  }, {
    title: 'Photo 5',
    description: 'Ugly photo of apartment 5',
    city: 'Sydney',
    country: 'Australia',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 30,
    profit_sharing: 30,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/5.jpg',
    user: users.second
  }, {
    title: 'Photo 6',
    description: 'Painting of apartment 6',
    city: 'Tokyo',
    country: 'Japan',
    type_art: 'Photography',
    style: 'Modern',
    price: 90,
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    profit_sharing: 50,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/6.jpg',
    user: users.second
  }, {
    title: 'Photo 7',
    description: 'Beautiful painting of apartment 7',
    city: 'Beijing',
    country: 'China',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 80,
    profit_sharing: 30,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/7.jpg',
    user: users.second
  }, {
    title: 'Photo 8',
    description: 'Acrylic painting of apartment 8',
    city: 'Beijing',
    country: 'China',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 70,
    profit_sharing: 55,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/8.jpg',
    user: users.second
  }, {
    title: 'Photo 9',
    description: 'Ugly painting of apartment 9',
    city: 'Beijing',
    country: 'China',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 75,
    profit_sharing: 35,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/9.jpg',
    user: users.second
  }, {
    title: 'Photo 10',
    description: 'Sculpture of apartment 10',
    city: 'Johannesburg',
    country: 'South Africa',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 85,
    profit_sharing: 35,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/10.jpg',
    user: users.second
  }, {
    title: 'Photo 11',
    description: 'Beautiful painting of apartment 11',
    city: 'Nairobi',
    country: 'Kenya',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 60,
    profit_sharing: 60,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/11.jpg',
    user: users.last
  }, {
    title: 'Photo 12',
    description: 'Painting of apartment 12',
    city: 'Perth',
    country: 'Australia',
    type_art: 'Photography',
    style: 'Modern',
    category: 'Style',
    condition: 'New',
    year: 2020,
    height: 200,
    length: 100,
    width: 10,
    price: 24,
    profit_sharing: 33,
    image_url: 'https://cdn.altcademy.com/assets/images/medium/airbnb_clone/12.jpg',
    user: users.last
  }
])
